import { createClient } from '@supabase/supabase-js';
import { execSync, spawn } from 'child_process';
import fs from 'fs';

const SUPABASE_URL = 'https://tiuwfhkrjvtkshebdwlp.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_YhLxIyNN7tsS2ixSnGfRUw_TF4EsRf-';
const client = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const SHREE_RAM_RESTAURANT_ID = '49ec41ff-3aa0-4022-94f0-b5fb57f70db5';
const TABLE_1_ID = 'aca0a9ac-119a-42bf-931f-2bdd1b53f3cf';
const DEVICE_SERIAL = 'RZCW80KCC8B';

// REAL NATIVE FCM DEVICE TOKEN GENERATED BY PHYSICAL PHONE (SM-E176B)
const NATIVE_FCM_TOKEN = 'ceLGp3FYRYWKwFssj0wE_1:APA91bF2SIJ70QGqDz9X-ACYsdezUHlkRArHB4bQB8e7EZAHyfz59Cl28f2nd2GA7DuhUo_mh59MulshAFOGp-UPjcnNzUzaeVSuHqduks4qKxnvMUO7Do8';

async function testNativeFcmKilledPush() {
  console.log('====================================================');
  console.log('   DIRECT NATIVE FCM KILLED STATE BELL ALERT TEST   ');
  console.log('====================================================\n');

  console.log(`Target User: nakshatra1233@gmail.com`);
  console.log(`Native Device FCM Token (Redacted): ceLGp3FY...uDo8`);

  // 1. Force Stop App to ensure 100% Killed State
  console.log('\nStep 1: Force stopping com.smartdine.mobile for 100% Killed State...');
  try {
    execSync(`adb -s ${DEVICE_SERIAL} shell am force-stop com.smartdine.mobile`);
  } catch (e) {}

  await new Promise(r => setTimeout(r, 1000));

  // Clear logcat buffer for fresh trace
  try { execSync(`adb -s ${DEVICE_SERIAL} logcat -c`); } catch (e) {}

  // 2. Start Screen Recording
  console.log('Step 2: Starting 15-second MP4 continuous screen recording on device...');
  const screenRec = spawn('adb', ['-s', DEVICE_SERIAL, 'shell', 'screenrecord', '--time-limit=15', '/data/local/tmp/native_fcm_proof.mp4']);
  await new Promise(r => setTimeout(r, 1500));

  const now = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' });

  // 3. Create DB Customer Call
  const { data: call } = await client.from('customer_requests').insert({
    restaurant_id: SHREE_RAM_RESTAURANT_ID,
    table_id: TABLE_1_ID,
    table_name: 'Table 1',
    type: 'call_waiter',
    status: 'pending',
    created_at: new Date().toISOString()
  }).select();

  console.log(`\nStep 3: [DB SUCCESS] Created Customer Call ID: ${call?.[0]?.id} for Table 1`);

  // 4. Dispatch Direct FCM Legacy API Push
  console.log('Step 4: Dispatching Direct FCM Push via Google FCM Endpoint...');
  const start = Date.now();
  const fcmRes = await fetch('https://fcm.googleapis.com/fcm/send', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'key=AIzaSyBo6kNedWGuZQuuDHlg2zVEHTgOem0FGcY'
    },
    body: JSON.stringify({
      to: NATIVE_FCM_TOKEN,
      priority: 'high',
      notification: {
        title: `🔔 WAITER CALL ALERT (${now})`,
        body: `Customer at Table 1 needs assistance! (Shree Ram)`,
        sound: 'order_tune',
        channel_id: 'smartdine_waiter_v2',
        android_channel_id: 'smartdine_waiter_v2'
      },
      data: {
        notificationType: 'CUSTOMER_CALL',
        requestId: call?.[0]?.id,
        timestamp: String(Date.now())
      }
    })
  });

  const fcmText = await fcmRes.text();
  const latency = Date.now() - start;
  console.log(`[DIRECT FCM RESPONSE Status: ${fcmRes.status}] Latency: ${latency}ms | Body:`, fcmText);

  // 5. Capture Logcat Trace
  await new Promise(r => setTimeout(r, 2000));
  console.log('\nStep 5: Capturing ADB Logcat trace for FirebaseMessaging / NotificationManager...');
  let logcatTrace = '';
  try {
    const rawLogcat = execSync(`adb -s ${DEVICE_SERIAL} logcat -d`).toString();
    const matches = rawLogcat.split('\n').filter(l =>
      l.includes('FirebaseMessaging') ||
      l.includes('NotificationManager') ||
      l.includes('FCM') ||
      l.includes('com.smartdine.mobile') ||
      l.includes('SoundCraft') ||
      l.includes('VibratorManagerService')
    );
    logcatTrace = matches.slice(-20).join('\n');
    console.log('ADB Logcat Output:\n', logcatTrace);
  } catch (e) {
    console.log('Logcat Warning:', e.message);
  }

  // 6. Finish Screen Recording and Pull Video
  console.log('\nStep 6: Waiting for MP4 screen recording to complete...');
  await new Promise(r => setTimeout(r, 9000));

  try {
    execSync(`adb -s ${DEVICE_SERIAL} pull /data/local/tmp/native_fcm_proof.mp4 native_fcm_proof.mp4`);
    fs.copyFileSync('native_fcm_proof.mp4', 'C:\\Users\\DELL\\.gemini\\antigravity\\brain\\af631f2d-472c-4b1a-a400-9353bd6e2483\\native_fcm_proof.mp4');
    console.log('Successfully saved native_fcm_proof.mp4 to artifacts directory!');
  } catch (e) {
    console.log('Video Pull Warning:', e.message);
  }

  console.log('\n====================================================');
  console.log('   DIRECT NATIVE FCM TEST COMPLETE                   ');
  console.log('====================================================');
}

testNativeFcmKilledPush();
