/**
 * Phase-28: Founder Control Center — Demo Errors & System Error Seed Data
 * Provides investor-grade realistic error scenarios with one-click recovery.
 */

import type { SystemErrorItem, ErrorAnalytics } from './types';

export const INITIAL_DEMO_ERROR: SystemErrorItem = {
  id: 'ERR-0007',
  orderId: 'A7K-26D00002',
  tableName: 'Table 12',
  time: '2 min ago',
  createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  severity: 'critical',
  status: 'active',
  title: 'Kitchen Update Failed',
  cause: 'Network timeout between Kitchen Queue and Preparing.',
  impact: [
    'Order delayed in kitchen prep queue',
    'Assigned waiter not notified of status change',
    'Inventory already reserved and locked',
  ],
  suggestedFix: 'Retry kitchen synchronization.',
  correlationId: 'corr_A7K-26D00002_err',
  apiEndpoint: '/api/staff/update-order-status',
  httpStatus: '504 Gateway Timeout',
  retryCount: 0,
  durationMs: 12450,
  failedNodeId: 'kitchen_queue',
  targetNodeId: 'order_preparing',
};

export const RESOLVED_ERRORS_SEED: SystemErrorItem[] = [
  {
    id: 'ERR-0006',
    orderId: 'A7K-26D00001',
    tableName: 'Table 14',
    time: '18 min ago',
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    severity: 'critical',
    status: 'resolved',
    title: 'Payment Webhook Handshake Failure',
    cause: 'Razorpay webhook signature verification retry required during peak traffic.',
    impact: ['Bill status temporarily desynced', 'Ledger pending confirmation'],
    suggestedFix: 'Auto-reconciled via polling endpoint.',
    correlationId: 'corr_A7K-26D00001_pay',
    apiEndpoint: '/api/webhooks/razorpay',
    httpStatus: '200 OK (Recovered)',
    retryCount: 1,
    durationMs: 4200,
    failedNodeId: 'payment',
    targetNodeId: 'bill_closed',
  },
  {
    id: 'ERR-0005',
    orderId: 'A7K-26D00003',
    tableName: 'Table 4',
    time: '45 min ago',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    severity: 'warning',
    status: 'resolved',
    title: 'KDS Station Sync Delay',
    cause: 'Station #2 WebSocket disconnected temporarily under heavy load.',
    impact: ['KDS display lag of 28s'],
    suggestedFix: 'Channel re-subscribed automatically.',
    correlationId: 'corr_A7K-26D00003_kds',
    apiEndpoint: '/api/staff/table-assignments',
    httpStatus: '200 OK (Recovered)',
    retryCount: 1,
    durationMs: 2800,
    failedNodeId: 'live_orders',
    targetNodeId: 'kitchen_queue',
  },
  {
    id: 'ERR-0004',
    orderId: 'A7K-26D00004',
    tableName: 'Table 16',
    time: '1h ago',
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    severity: 'info',
    status: 'resolved',
    title: 'Waiter FCM Push Ack Delay',
    cause: 'Mobile client was in low power background mode during idle shift.',
    impact: ['15s dispatch delay before waiter accepted call'],
    suggestedFix: 'Notification delivered via backup SMS channel.',
    correlationId: 'corr_A7K-26D00004_fcm',
    apiEndpoint: '/api/push/dispatch',
    httpStatus: '200 OK (Recovered)',
    retryCount: 1,
    durationMs: 1520,
    failedNodeId: 'push_notifications',
    targetNodeId: 'waiter_assigned',
  },
  {
    id: 'ERR-0003',
    orderId: 'A7K-26D00005',
    tableName: 'Table 2',
    time: '2h ago',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    severity: 'warning',
    status: 'resolved',
    title: 'Stock Deduction Lock Contention',
    cause: 'Simultaneous order reservation on Mozzarella Cheese recipe ingredient.',
    impact: ['Transaction queued for 34s before idempotency lock released'],
    suggestedFix: 'Idempotent retry succeeded on second attempt.',
    correlationId: 'corr_A7K-26D00005_inv',
    apiEndpoint: '/api/inventory/reserve',
    httpStatus: '200 OK (Recovered)',
    retryCount: 1,
    durationMs: 3400,
    failedNodeId: 'inventory',
    targetNodeId: 'order_created',
  },
  {
    id: 'ERR-0002',
    orderId: 'A7K-26D00006',
    tableName: 'Table 8',
    time: '3h ago',
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    severity: 'info',
    status: 'resolved',
    title: 'Cart Session Idle Expiry',
    cause: 'Customer inactive for 15 minutes before checkout.',
    impact: ['Session refreshed automatically with preserved cart items'],
    suggestedFix: 'Session heartbeat extended.',
    correlationId: 'corr_A7K-26D00006_sess',
    apiEndpoint: '/api/customer/orders',
    httpStatus: '200 OK (Recovered)',
    retryCount: 1,
    durationMs: 1800,
    failedNodeId: 'cart',
    targetNodeId: 'checkout',
  },
  {
    id: 'ERR-0001',
    orderId: 'A7K-26D00007',
    tableName: 'Table 10',
    time: '4h ago',
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    severity: 'warning',
    status: 'resolved',
    title: 'Receipt Printer Network Offline',
    cause: 'Thermal printer buffer overrun on ESC/POS socket.',
    impact: ['Physical print delayed by 55s; digital invoice sent immediately via WhatsApp'],
    suggestedFix: 'Socket re-initialized; print queue cleared.',
    correlationId: 'corr_A7K-26D00007_prn',
    apiEndpoint: '/api/orders/print-receipt',
    httpStatus: '200 OK (Recovered)',
    retryCount: 1,
    durationMs: 5500,
    failedNodeId: 'session_closed',
    targetNodeId: 'reports',
  },
];

export const DEMO_ERROR_ANALYTICS: ErrorAnalytics = {
  totalErrorsToday: 7,
  resolvedCount: 6,
  avgRecoveryTimeSec: 42,
  criticalCount: 1,
  recoveryRatePercent: 98.4,
};
